name: Testing matrices and environment variables

on:
  push:
    branches:
      - '*'

jobs:
    # dev:
    #   uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
    #   with:
    #     ENV: dev
    #   secrets:
    #     NAME: ${{ secrets.NAME }}
    # stage:
    #   uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
    #   with:
    #     ENV: stage
    #   secrets:
    #     NAME: ${{ secrets.NAME }}


    # test-job:
    #   name: Test
    #   runs-on: ubuntu-latest
    #   environment: dev
    #   steps:
    #   - name: Set outputs
    #     id: vars
    #     run: echo ${GITHUB_SHA::7}
  dev:
    uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
    with:
      ENV: $GITHUB_SHA
    secrets:
      NAME: ${{ secrets.NAME }}