name: Testing matrices and environment variables

on:
  push:
    branches:
      - '*'

jobs:
    # test-job:
    #   name: Test
    #   runs-on: ubuntu-latest
    #   strategy:
    #     matrix:
    #       environments: [dev, stage]
    #   environment: ${{ matrix.environments }}
    #   steps:
    #   - run: |
    #       if [[ "${{ secrets.NAME }}" == "dev" ]]
    #       then
    #         echo hi
    #       fi
    #       echo ${{ matrix.environments }}

    test:
      uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
      with:
        ENV: dev
    # test-job:
    #   name: Test
    #   runs-on: ubuntu-latest
    #   environment: dev
    #   steps:
    #   - run: |
    #       echo ${{ env.NAME }}
