name: Testing matrices and environment variables

on:
  push:
    branches:
      - '*'

jobs:
    # dev:
    #   uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
    #   with:
    #     ENV: dev
    #   secrets:
    #     NAME: ${{ secrets.NAME }}
    # stage:
    #   uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
    #   with:
    #     ENV: stage
    #   secrets:
    #     NAME: ${{ secrets.NAME }}


    # test-job:
    #   name: Test
    #   runs-on: ubuntu-latest
    #   environment: dev
    #   steps:
    #   - name: Set outputs
    #     id: vars
    #     run: echo ${GITHUB_SHA::7}
  get-sha:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-sha.outputs.sha}}
    steps:
    - id: get-sha
      run: |
        export SHORT_SHA=${GITHUB_SHA::7}
        echo $SHORT_SHA
        echo "::set-output name=sha::$(echo $SHORT_SHA)"

  temp:
    runs-on: ubuntu-latest
    needs: get-sha
    steps:
    - run: |
        echo ${{ needs.get-sha.outputs.sha }}

  dev:
    needs: temp
    uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
    with:
      ENV: dfghdfgh
    secrets:
      NAME: ${{ secrets.NAME }}