name: Testing matrices and environment variables

on:
  push:
    branches:
      - '*'
jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup matrix combinations
        id: setup-matrix-combinations
        run: |
          # MATRIX_PARAMS_COMBINATIONS='
          #   {"foo": "foo-1", "bar": "bar-1"},
          #   {"foo": "foo-1", "bar": "bar-2"},
          #   {"foo": "foo-2", "bar": "bar-1"},
          # '

          MATRIX_PARAMS_COMBINATIONS='
            {"dir": "."},
            {"dir":"module/stuff"}
          '
          echo ::set-output name=matrix-combinations::{\"include\":[$MATRIX_PARAMS_COMBINATIONS]}
    outputs:
      matrix-combinations: ${{ steps.setup-matrix-combinations.outputs.matrix-combinations }}
  matrix-job:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix-combinations) }}
    steps:
      - run: |
          echo dir=${{ matrix.dir }}
    # dev:
    #   uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
    #   with:
    #     ENV: dev
    #   secrets:
    #     NAME: ${{ secrets.NAME }}
    # stage:
    #   uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
    #   with:
    #     ENV: stage
    #   secrets:
    #     NAME: ${{ secrets.NAME }}


    # test-job:
    #   name: Test
    #   runs-on: ubuntu-latest
    #   environment: dev
    #   steps:
    #   - name: Set outputs
    #     id: vars
    #     run: echo ${GITHUB_SHA::7}
  # get-sha:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     sha: ${{ steps.get-sha.outputs.sha}}
  #   steps:
  #   - id: get-sha
  #     run: |
  #       export SHORT_SHA=${GITHUB_SHA::7}
  #       echo $SHORT_SHA
  #       echo "::set-output name=sha::$(echo $SHORT_SHA)"

  # temp:
  #   runs-on: ubuntu-latest
  #   # needs: get-sha
  #   steps:
  #   - run: |
  #       apt-get install sudo
  #       sudo echo $GITHUB_ENV

  dev:
    uses: edw1nzhao/zhao-workflows/.github/workflows/template.yml@main
    with:
      ENV: dev
      SOMETHING: SOMETING
    secrets:
      EDWIN: ${{ secrets.EDWIN }}